import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:journaling/core/app.dart';
import 'package:journaling/core/utils/storage_utils.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await StorageUtils.init();
  runApp(const MyApp()); // Your main app widget
}
